name: Build smoochiee firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ§¬ Checkout code
      uses: actions/checkout@v3

    - name: ğŸ Set up Python & install PlatformIO
      run: |
        pip install -U platformio

    - name: ğŸ”¨ Build smoochiee firmware
      run: platformio run -e smoochiee-board

    - name: ğŸ“¦ Upload firmware bin
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/smoochiee-board/firmware.bin
        retention-days: 7
